// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.18408
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace ZiZhuJY.ResX_Aggregator.Core.Specs
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("ResXLoader")]
    public partial class ResXLoaderFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "ResXLoader.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "ResXLoader", "", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Load resources from resx files")]
        [NUnit.Framework.CategoryAttribute("file")]
        public virtual void LoadResourcesFromResxFiles()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Load resources from resx files", new string[] {
                        "file"});
#line 4
this.ScenarioSetup(scenarioInfo);
#line 5
 testRunner.Given("a resx-aggregator file full path is <.\\index.cshtml.resx-aggregator>", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Value"});
            table1.AddRow(new string[] {
                        "CloseLinkDialog",
                        "Stäng"});
            table1.AddRow(new string[] {
                        "CloseMsg",
                        "Stäng meddelandefönstret"});
            table1.AddRow(new string[] {
                        "CloseTips",
                        "Stäng hjälp"});
#line 6
 testRunner.And("there is a resx file which full path is <.\\index.cshtml.resx> has these contents:" +
                    "", ((string)(null)), table1, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Value"});
            table2.AddRow(new string[] {
                        "CloseLinkDialog",
                        "Close"});
            table2.AddRow(new string[] {
                        "CloseMsg",
                        "Close message window"});
            table2.AddRow(new string[] {
                        "CloseTips",
                        "Close help"});
#line 11
 testRunner.And("there is a resx file which full path is <.\\index.cshtml.en-US.resx> has these con" +
                    "tents:", ((string)(null)), table2, "And ");
#line 16
 testRunner.When("I load the resx-aggregator file", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "default",
                        "en-US"});
            table3.AddRow(new string[] {
                        "CloseLinkDialog",
                        "Stäng",
                        "Close"});
            table3.AddRow(new string[] {
                        "CloseMsg",
                        "Stäng meddelandefönstret",
                        "Close message window"});
            table3.AddRow(new string[] {
                        "CloseTips",
                        "Stäng hjälp",
                        "Close help"});
#line 17
 testRunner.Then("the dictionary in the ResXLoader should be", ((string)(null)), table3, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
